' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/02/24 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Full Robot Assem.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\Master Sketch - Converyor V2.SLDPRT", 1, 0, "", longstatus, longwarnings)

' Redraw
Part.GraphicsRedraw2
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07969481363885891345, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03811491087075860595, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03464991897341691829, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03118492707607522021, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03811491087075860595, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03811491087075860595, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03811491087075860595, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, -0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03118492707607522021, 0.1372857830123635214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.2440636142442018375, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03464991897341691829, 0.2440636142442018375, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03464991897341691829, 0.3203334936955148926, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04850988656278368283, 0.404230361091959256, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0554398703574670651, 0.404230361091959256, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, 0.1067778312318382883, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03464991897341691829, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03811491087075860595, 0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04850988656278368283, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03118492707607522021, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03118492707607522021, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03118492707607522021, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03464991897341691829, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03118492707607522021, 0.1906746986282826795, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0.1449127709574948297, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02771993517873353255, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.09915084328670699387, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.0838968673964443773, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.1144048191769695966, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0838968673964443773, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02425494328139184141, 0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, 0.09915084328670699387, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, 0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, 0.0838968673964443773, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.1220318071221009187, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.0838968673964443773, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02425494328139184141, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02771993517873353255, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.1067778312318382883, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.1449127709574948297, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02425494328139184141, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, 0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, 0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, 0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04157990276810030056, 0.1830477106831513712, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, 0.1144048191769695966, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, 0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, 0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, 0.06864289150618176072, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, 0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006929983794683383137, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, 0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03464991897341691829, 0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06929983794683383658, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03464991897341691829, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02425494328139184141, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01039497569202507514, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003464991897341691569, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03811491087075860595, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02771993517873353255, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04157990276810030056, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02078995138405015028, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01385996758936676627, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1372857830123635214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1144048191769695966, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006929983794683383137, 0.1296587950672322131, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, 0.09152385534157568558, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, 0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003464991897341691569, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, 0.04576192767078784279, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02425494328139184141, 0, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03464991897341691829, -0.007626987945131307421, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02771993517873353255, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03464991897341691829, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02425494328139184141, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02771993517873353255, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02078995138405015028, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03811491087075860595, -0.06101590356105045937, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03118492707607522021, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02771993517873353255, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03464991897341691829, -0.05338891561591914414, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04157990276810030056, -0.07626987945131306901, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03118492707607522021, -0.0381349397256565345, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02425494328139184141, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.0228809638353939214, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01385996758936676627, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01039497569202507514, -0.03050795178052522968, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01732495948670845914, -0.01525397589026261484, -0.3868909318740634262, 0.01089715209144515029, 0.2520350172662446653

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Master Sketch - Converyor V2.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
