' ******************************************************************************
' swxJRNL.swj - journal recorded on 01/29/24 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "conveyor v2 assembly.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01482549342143501397, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01482549342143501397, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.01482549342143501397, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.01482549342143501397, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.02223824013215252096, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02223824013215252096, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.01482549342143501397, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.01482549342143501397, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.02223824013215252096, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.3111136892005106347, 0.7100231180852745183, -0.2033114562665900849

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1580613803837368492, 0.08895296052861008385, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, 0.02965098684287002795, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, 0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.04447648026430504192, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0.04447648026430504192, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.02965098684287002795, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02965098684287002795, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02965098684287002795, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.04447648026430504192, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.05188922697502254544, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.04447648026430504192, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.05188922697502254544, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.06671472039645755248, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.07412746710717506293, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.08154021381789257339, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.06671472039645755248, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.08154021381789257339, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.08895296052861008385, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.07412746710717506293, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.07412746710717506293, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.0593019736857400559, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.0593019736857400559, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.03706373355358753147, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02965098684287002795, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02965098684287002795, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02223824013215252096, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, -0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.01482549342143501397, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.007412746710717506987, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3157965009157237546, 0.7044423604003782202, -0.1951226429246162297

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02965098684287002795, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02965098684287002795, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.02223824013215252096, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05188922697502254544, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03706373355358753147, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.3685324979866564377, 0.6415940464320328829, -0.194410326809837386

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0927751580513237889, -0.04447648026430504192
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04123340357836613457, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03436116964863843853, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Redraw
Part.GraphicsRedraw2
boolstatus = Part.Extension.SelectByRay(-0.2151978902076052691, 0.8152552156553838358, -0.1905000000000427463, 0.4166144142736343259, -0.7536403745925539521, -0.5083882528180916349, 0.0006868322014842765961, 2, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.161497497348600666, 0.3187481085608527831
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.07412746710717506293
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, 0.04447648026430504192
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.05188922697502254544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, 0.05188922697502254544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.02965098684287002795

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.1928972696138089304, 0.8347701507471469995, 0.1905000000000427463, 0.6897941817155768263, -0.3951362087378630372, 0.6066723690886258735, 0.0009629952488287072234, 2, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05841398840268535037, -0.05188922697502254544, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02965098684287002795, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, -0.04447648026430504192, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, -0.02965098684287002795, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02965098684287002795, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.02223824013215252096, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.01482549342143501397, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.01482549342143501397, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.02223824013215252096, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.01482549342143501397, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.2055123853705822512, 0.8359123576137221789, 0.2105319208839091516

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.SetPickMode
Part.ClearSelection2 True
Part.SetPickMode
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Full Robot Assem.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Full Robot Assem.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
boolstatus = Part.Extension.SelectByID2("    (3)-1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("    (3)-1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Assem V1-1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Intake V5 Assem-1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True

' Named View
Part.ShowNamedView2 "*Back", 2
Part.ViewZoomtofit2
boolstatus = Part.Extension.SelectByID2("  NOTE   -1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06872233929727687707, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.05188922697502254544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.4744157894859204472

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("  NOTE   -1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Assem V1-1@Full Robot Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\ .SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 " .SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
boolstatus = Part.Extension.SelectByID2("Thin poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line81@Poly", "EXTSKETCHSEGMENT", -0.2461732937736198779, 0.756113651872582504, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line81@Poly", "EXTSKETCHSEGMENT", -0.234654636928240623, 0.7698410525499232993, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Thin poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Thin poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditSketch
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Profiles", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Profiles", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditSketch
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Thin poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.BlankSketch
boolstatus = Part.Extension.SelectByID2("Line81@Poly", "EXTSKETCHSEGMENT", -0.3733542563704542183, 0.6045452827882127345, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.EditSketch
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Thin poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.UnblankSketch
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("Line74@Poly", "EXTSKETCHSEGMENT", -0.4801827072600434176, 0.3860217846089279425, 0, False, 0, Nothing, 0)

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Part.ClearSelection2 True
boolstatus = Part.SetUserPreferenceToggle(swUserPreferenceToggle_e.swViewDisplayHideAllTypes, True)

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SelectByID2("Thin poly", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True

' Named View
Part.ShowNamedView2 "*Front", 1
Part.ViewZoomtofit2
boolstatus = Part.SetUserPreferenceToggle(swUserPreferenceToggle_e.swViewSketchRelations, True)
boolstatus = Part.SetUserPreferenceToggle(swUserPreferenceToggle_e.swViewDisplayHideAllTypes, False)

' Redraw
Part.GraphicsRedraw2

' New Document
Dim swSheetWidth As Double
swSheetWidth = 0
Dim swSheetHeight As Double
swSheetHeight = 0
Set Part = swApp.NewDocument("C:\ProgramData\SolidWorks\SOLIDWORKS 2022\templates\Part.prtdot", 0, swSheetWidth, swSheetHeight)
Dim swPart As PartDoc
Set swPart = Part
swApp.ActivateDoc2 "Part1", False, longstatus
Set Part = swApp.ActiveDoc
Dim myFeature As Object
Set myFeature = Part.InsertPart3("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\ .SLDPRT", 97, "Default")
Part.ClearSelection2 True

' Redraw
Part.GraphicsRedraw2

' Redraw
Part.GraphicsRedraw2

' Redraw
Part.GraphicsRedraw2

' Redraw
Part.GraphicsRedraw2

' Named View
Part.ShowNamedView2 "*Front", 1
Part.ViewZoomtofit2
Part.SketchManager.InsertSketch True
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("-0.205226", "0.868038", "0.000000", "-0.210490", "0.872344", "0.000000")
boolstatus = Part.Extension.SelectByID2("Line84@Poly- ", "EXTSKETCHSEGMENT", -0.1672020027331297953, 0.8586312868426364542, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line88@Poly- ", "EXTSKETCHSEGMENT", -0.1694680211271784032, 0.8579218874626589608, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line83@Poly- ", "EXTSKETCHSEGMENT", -0.1852675448230883259, 0.8600007127612983027, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line91@Poly- ", "EXTSKETCHSEGMENT", -0.1838891500391304223, 0.8585319720433721713, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line90@Poly- ", "EXTSKETCHSEGMENT", -0.1831572498128698767, 0.8483642978359732245, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line89@Poly- ", "EXTSKETCHSEGMENT", -0.171269612351515943, 0.8484918309596294339, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line86@Poly- ", "EXTSKETCHSEGMENT", -0.1821139103265075054, 0.844878017479109289, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Line85@Poly- ", "EXTSKETCHSEGMENT", -0.1722726536008613862, 0.8441850052934809501, 0, True, 0, Nothing, 0)
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)
Part.ClearSelection2 True

' Previous View
Part.ViewOrientationUndo

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.06671472039645755248
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.08154021381789257339
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.04447648026430504192
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.07412746710717506293
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.05188922697502254544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myFeature = Part.FeatureManager.FeatureExtrusion2(True, False, False, 6, 0, 0.3535679999999999934, 0.01000000000000000021, False, False, False, False, 0.01745329251994333364, 0.01745329251994333364, False, False, False, False, True, True, True, 0, 0, False)
Part.SelectionManager.EnableContourSelection = False
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02965098684287002795, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02965098684287002795, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02223824013215252096, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02223824013215252096, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02223824013215252096, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02223824013215252096, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02965098684287002795, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02965098684287002795, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02965098684287002795, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.02223824013215252096, -0.178443436551447121, 0.868393017479853313, -0.09184638713253434616

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Save As
longstatus = Part.SaveAs3("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\top profile (right plane).SLDPRT", 0, 0)

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\conveyor v2 assembly.SLDASM", 2, 0, "", longstatus, longwarnings)
Set swAssembly = Part
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "conveyor v2 assembly.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc

' Insert Component
Dim AssemblyTitle As String
AssemblyTitle = Part.GetTitle
Dim tmpObj As ModelDoc2
Dim errors As Long
Set tmpObj = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\top profile (right plane).SLDPRT", 1, 32, "", errors, longwarnings)
Set Part = swApp.ActivateDoc3(AssemblyTitle, True, 0, errors)
Dim swInsertedComponent As Component2
Set swInsertedComponent = Part.AddComponent5("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\top profile (right plane).SLDPRT", 0, "", False, "", -0.5269327237037941813, 0.3310043722158297896, 0.007845103633371763863)
swApp.CloseDoc "C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\top profile (right plane).SLDPRT"
Dim TransformData() As Double
ReDim TransformData(0 To 15) As Double
TransformData(0) = 1
TransformData(1) = 0
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 1
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = 0
TransformData(10) = 0
TransformData(11) = 0
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
Dim TransformDataVariant As Variant
TransformDataVariant = TransformData
Dim swMathUtil As Object
Set swMathUtil = swApp.GetMathUtility()
Dim swTransform As Object
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
boolstatus = swInsertedComponent.SetTransformAndSolve2(swTransform)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.1037784539500450909, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.03706373355358753147, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02223824013215252096, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.02223824013215252096, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.02223824013215252096, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.02223824013215252096, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.02223824013215252096, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.2861091472082648579, 0.7397942653512359357, -0.1891254960423145448

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.2656177734358493581, 0.744908163486684316, -0.1905000000000995897, 0.6391996649317754908, -0.6145748662437224841, -0.4623002510626798012, 0.002396240337565448252, 2, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.03706373355358753147, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02965098684287002795, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.02965098684287002795, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.03706373355358753147, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.03706373355358753147, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.04447648026430504192, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.06671472039645755248, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.02965098684287002795, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.02965098684287002795, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01718058482431921927, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.3385823726732155592, 0.9199173340557535994, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.3385823726732155592, 0.9199173340557535994, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.2047282209679792686, 0.8123623387116367667, 0.1904999999999859028, 0.858409172867754533, -0.4536680720937779077, 0.2394138097504240337, 0.002396240337565448252, 2, True, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.1883193288231836959, 0.8563637382153501676, 0.06301481419987453592, 0.858409172867754533, -0.4536680720937779077, 0.2394138097504240337, 0.002396240337565448252, 2, False, 0, 0)
Part.OpenCompFile

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\GitHub\Crescendo-CAD\Systems\Conveyor\V2 Converyor\top profile (right plane).SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "top profile (right plane).SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Boss-Extrude1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ActivateSelectedFeature
boolstatus = Part.Extension.SelectByID2("Boss-Extrude1", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07559457322700456616, -0.2075569079000901818, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05154175447295766127, -0.08895296052861008385, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04810563750809381672, -0.06671472039645755248, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04123340357836613457, -0.04447648026430504192, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.03706373355358753147, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.01482549342143501397, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.02223824013215252096, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.02965098684287002795, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, 0, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.02223824013215252096, 0, 0, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1924225500323752669, -0.1556676809250676363, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05497787143782150582, -0.05188922697502254544, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.02223824013215252096, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, -0.02965098684287002795, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03436116964863843853, -0.01482549342143501397, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.007412746710717506987, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01482549342143501397, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.007412746710717506987, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.007412746710717506987, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1912249659848725969, 0.8520798579169195364, -0.04384883711696829778

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 " .SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "top profile (right plane).SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Full Robot Assem.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
swApp.ExitApp
End Sub
