' ******************************************************************************
' swxJRNL.swj - journal recorded on 01/22/24 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "V4 Assem.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SelectByID2("mecanum assem-1@V4 Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.1206663653383088786, 0.287971390237430569, -0.3192739872938261669, 0.9297253099011583144, 0.2823720748428625305, -0.2363828662956181936, 0.001406709276955375211, 1, False, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", -0.1206663653383088786, 0.287971390237430569, -0.3192739872938261669, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("mecanum assem-9@V4 Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Dim TransformData() As Double
ReDim TransformData(0 To 15) As Double
TransformData(0) = 0.8012488461407384355
TransformData(1) = -0.5983312515305674317
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 0
TransformData(5) = -1
TransformData(6) = 0.5983312515305675428
TransformData(7) = 0.8012488461407386575
TransformData(8) = 0
TransformData(9) = -0.07533874486742976606
TransformData(10) = 0.2035478897362731077
TransformData(11) = -0.2936645210132545203
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
Dim TransformDataVariant As Variant
TransformDataVariant = TransformData
Dim swMathUtil As Object
Set swMathUtil = swApp.GetMathUtility()
Dim swTransform As Object
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Dim swComp As Object
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.04447648026430504192
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.05188922697502254544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01482549342143501397

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.08323053971582794475, 0.2334539964959105873, 0.1741664174049901703, 0.7860774827558434374, 0.2898640946464031143, 0.5459496293057241045, 0.002430793630578888254, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.07583178988710415069, 0.2411083358340988525, 0.1738130800353019367, 0.7860774827558434374, 0.2898640946464031143, 0.5459496293057241045, 0.0006596213990464920227, 1, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Concentric15", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.DeSelectByID("", "GHOST_EDGE", 0, 0, 0)
boolstatus = Part.Extension.SelectByRay(-0.09177687198973671912, 0.2407745472351905391, 0.1741625587922612795, 0.7860774827558434374, 0.2898640946464031143, 0.5459496293057241045, 0.0001428191168784384622, 1, True, 0, 0)
boolstatus = Part.Extension.SelectByID2("Parallel8", "MATE", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.161497497348600666, 0.0593019736857400559, -0.113744354908249079, 0.2791096433390407583, 0.1700208155226050621
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.007412746710717506987, -0.113744354908249079, 0.2791096433390407583, 0.1700208155226050621
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.113744354908249079, 0.2791096433390407583, 0.1700208155226050621

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.DeSelectByID("NullFeature, 178;NullFeature, 168;NullFeature, 419;NullFeature, 306;NullFeature, 302;", "GHOST_FACE", 0, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.05188922697502254544, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, -0.02965098684287002795, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, -0.02223824013215252096, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.01482549342143501397, -0.1277305255837859477, 0.2919404445314484065, 0.206637669589952111

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04810563750809381672, 0.0593019736857400559, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03092505268377459399, -0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.01482549342143501397, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.1102065511131229414, 0.2793799260692466646, 0.1709565880564696272

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.1108864182792927977, 0.2804341129940013388, 0.1974016313969855219, -0.2357865063489432977, -0.06425611002608357103, 0.9696782331000709521, 9.340285917552519732e-05, 2, True, 0, 0)
boolstatus = Part.Extension.SelectByID2("Distance2", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Distance2", "MATE", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03092505268377459399, 0.1408421875036326154, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03706373355358753147, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03706373355358753147, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.03706373355358753147, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.1111912006607625875, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.07412746710717506293, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.07412746710717506293, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07412746710717506293, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.08895296052861008385, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.1853186677679376504, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.1037784539500450909, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.1037784539500450909, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.07412746710717506293, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.08154021381789257339, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.07412746710717506293, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04447648026430504192, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.03706373355358753147, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.02965098684287002795, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01030835089459153364, 0.03706373355358753147, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.09547826545265536424, 0.2705466578673707545, 0.3373913441606077868

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.1853186677679376504, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.05188922697502254544, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.04447648026430504192, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.06671472039645755248, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02965098684287002795, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.03706373355358753147, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.05188922697502254544, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.03706373355358753147, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02965098684287002795, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.03706373355358753147, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02223824013215252096, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.007412746710717506987, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01482549342143501397, -0.1250050137582547904, 0.2806374044282069491, -0.02638885695193948777

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.DeSelectByID("NullFeature, 29;NullFeature, 36;NullFeature, 20;NullFeature, 21;NullFeature, 217;NullFeature, 23;NullFeature, 235;NullFeature, 296;NullFeature, 64;NullFeature, 394;NullFeature, 122;NullFeature, 415;NullFeature, 451;NullFeature, 128;NullFeature, 200;NullFeature, 30;NullFeature, 403;NullFeature, 454;NullFeature, 127;NullFeature, 172;NullFeature, 10;NullFeature, 9;NullFeature, 129;NullFeature, 116;NullFeature, 445;NullFeature, 201;NullFeature, 115;NullFeature, 220;NullFeature, 411;NullFeature, 402;NullFeature, 311;NullFeature, 291;NullFeature, 396;NullFeature, 185;NullFeature, 308;NullFeature, 437;NullFeature, 354;NullFeature, 387;NullFeature, 294;NullFeature, 226;NullFeature, 453;NullFeature, 424;NullFeature, 370;NullFeature, 339;NullFeature, 406;NullFeature, 320;NullFeature, 146;NullFeature, 191;NullFeature, 90;NullFeature, 425;NullFeature, 8;NullFeature, 131;NullFeature, 333;NullFeature, 107;NullFeature, 105;NullFeature, 456;NullFeature, 436;NullFeature, 249;NullFeature, _
50;NullFeature, 190;NullFeature, 382;NullFeature, 241;NullFeature, 140;NullFeature, 401;NullFeature, 334;NullFeature, 61;NullFeature, 177;NullFeature, 135;NullFeature, 17;NullFeature, 376;NullFeature, 160;NullFeature, 301;NullFeature, 149;NullFeature, 297;NullFeature, 358;NullFeature, 28;NullFeature, 312;NullFeature, 113;NullFeature, 151;NullFeature, 318;NullFeature, 338;NullFeature, 434;", "GHOST_FACE", 0, 0, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.1181805656410119809, 0.2921145111597880373, 0.1759873883387683691, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("am-1526 500Hex HD Collar Clamp-2@V4 Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = 0.910704201165367544
TransformData(1) = -0.4130591458614004119
TransformData(2) = 0
TransformData(3) = 0.4130591458614004119
TransformData(4) = 0.910704201165367544
TransformData(5) = 0
TransformData(6) = 0
TransformData(7) = 0
TransformData(8) = 1
TransformData(9) = -0.02569000240768297763
TransformData(10) = 0.2294915918453971915
TransformData(11) = 0.2036819558351095627
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.1066747672385304213, 0.2966681966828943473, 0.02933764752347656213, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("mecanum assem-1@V4 Assem", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
ReDim TransformData(0 To 15) As Double
TransformData(0) = -0.1805297416903629548
TransformData(1) = -0.9835695259437488014
TransformData(2) = 0
TransformData(3) = 0
TransformData(4) = 0
TransformData(5) = -1
TransformData(6) = 0.9835695259437488014
TransformData(7) = -0.1805297416903629548
TransformData(8) = 0
TransformData(9) = -0.1133476903275744269
TransformData(10) = 0.2803632397920404751
TransformData(11) = 0.22598557928505425
TransformData(12) = 1
TransformData(13) = 0
TransformData(14) = 0
TransformData(15) = 0
TransformDataVariant = TransformData
Set swMathUtil = swApp.GetMathUtility()
Set swTransform = swMathUtil.CreateTransform((TransformDataVariant))
Set swComp = Part.SelectionManager.GetSelectedObjectsComponent4(1, -1)
boolstatus = swComp.SetTransformAndSolve2(swTransform)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02965098684287002795, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.03706373355358753147, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.03706373355358753147, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02965098684287002795, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, 0.02965098684287002795, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007412746710717506987, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02223824013215252096, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01482549342143501397, -0.106260388056625743, 0.2900864721325930873, 0.1794631950204745863

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.1171164134879632002, 0.2986102627056084202, 0.2017926676180650247, 0.8134253335126298001, 0.1083934683402458382, 0.571480605813565079, 0.0005952226011684011529, 2, True, 0, 0)
boolstatus = Part.Extension.SelectByID2("Coincident1@mecanum assem-1@V4 Assem", "MATE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Coincident1@mecanum assem-1@V4 Assem", "MATE", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.7635129112039031885
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1037784539500450909
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007412746710717506987

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.ClearSelection2 True
Part.AssemblyPartToggle
Part.EditAssembly
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
