' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/07/24 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "profile 1", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Save As
longstatus = Part.SaveAs3("C:\Users\USER\Documents\github\Crescendo-CAD\Outsourcing 2024\Chassis proflies\profile 1.STEP", 0, 2)
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.07412746710717506293
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.08895296052861008385
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.04447648026430504192
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.0593019736857400559
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.04447648026430504192
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03436116964863843853, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03092505268377459399, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03779728661350228308, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02748893571891075291, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02405281875404690836, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02061670178918306728, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04123340357836613457, 0.05188922697502254544
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05497787143782150582, 0.08895296052861008385
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05497787143782150582, 0.08895296052861008385
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, 0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03092505268377459399, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.08246680715673226914, 0.06671472039645755248
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04810563750809381672, 0.0593019736857400559

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Close Document
swPart = Nothing
Set Part = Nothing
swApp.CloseDoc "profile 1"

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\github\Crescendo-CAD\Full Robot Assem.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
swApp.ActivateDoc2 "Full Robot Assem", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.3779728661350228447, -0.1853186677679376504

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06872233929727687707, -0.2816843750072652308

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02748893571891075291, 0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02061670178918306728, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02405281875404690836, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01718058482431921927, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01718058482431921927, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01030835089459153364, -0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02965098684287002795
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.03706373355358753147
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003436116964863844114, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.006872233929727688227, -0.02223824013215252096
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01374446785945537645, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01030835089459153364, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.01482549342143501397
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, -0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0.007412746710717506987
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.006872233929727688227, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003436116964863844114, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Open
Set Part = swApp.OpenDoc6("C:\Users\USER\Documents\github\Crescendo-CAD\Systems\Chasiss\Outsourcing\profile 2.SLDPRT", 1, 0, "", longstatus, longwarnings)
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "profile 2", False, longstatus
Set Part = swApp.ActiveDoc
